# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoNews
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~> 5.0'
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'FeedKit', '~> 9.0'
  pod 'SwiftCharts', '~> 0.6.5'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end
